version: "3"

services:
  nodeapp:
    container_name: nodeapp
    image: nodeapp
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
